# set a base image

# set the shell to bash

# set the ros_distro version

# install some useful packages and upgrade existing ones

# install ros packages
# see ../docs/installing_ros_packages.md for alternatives

# change the working directory

# setup a package from github


# setup .bashrc

# copy the entrypoint into the image


# run this script on startup
